export interface IMovie {
    movieId: number,
    originalTitle: string,
    title: string,
    titleHindi: string,
    releaseDate: string,
    tmdbId: string,
    imdbId: string,
    netflixId: number,
    plot: null,
    outline: string,
    outlineHindi: string,
    tagline: string,
    country: string,
    posterImageExternalUrl: string,
    backdropImageExternalUrl: string,
    logoImageExternalUrl: string,
    certification: string,
}